### ISSUE TITLE
Artifact delivery despite wrong certificate

### ISSUE THREAD

**Issue by sebplorenz** [FraunhoferISST/DataspaceConnector#156]
I'm getting the following error at the provider DSC when the consumer DSC is requesting data:

06:45:18.573 [http-nio-8080-exec-8] ERROR de.fraunhofer.isst.ids.framework.daps.TokenManagerService - Certificate of the Connector is missing aki/ski extensions!

I'm currently using the default certificates provided in the DSC repository.
I assume that the error is related to the consumer certificate. Maybe this should be stated clearly.
Even with that error the requested artifact is delivered to the consumer.
How can the delivery of the resource be avoided if the certificate is wrong?

**Comment by ghost** [comment]
Hello,

the error message is thrown from the `acquireToken` method of the IDS-Framework's `TokenManagerService`. This error message is thrown if there is a problem with the certificate of the connector which tries to send a message. Accordingly, it is an error on the provider connector's certificate, if you get the error at the provider DSC. As a result, the connector cannot get a valid DAT from the DAPS for the message the connector is trying to send, but sends the message out after logging the error anyway, with a note attached to the send message for the recipient that there is no valid DAT in the message.

With the future IDS-Framework version 5 and also the Unified-Library project, messages will no longer be sent without a valid DAT.

Preview IDS-Framework Version 5 (see major changes): https://github.com/International-Data-Spaces-Association/IDS-Connector-Framework/issues/14

Error throwing IDS-Framework class (Version 4.x.y): https://github.com/International-Data-Spaces-Association/IDS-Connector-Framework/blob/development/base/src/main/java/de/fraunhofer/isst/ids/framework/daps/TokenManagerService.java

**Comment by sebplorenz** [comment]
Hi @tmberthold, thanks for the explanation. In addition it should be mentioned that the delivery of the artifact can be prevented by setting the **ids:connectorDeployMode** to **idsc:PRODUCTIVE_DEPLOYMENT** in the **config.json** as explained here https://github.com/International-Data-Spaces-Association/DataspaceConnector/wiki/Deployment

**Comment by ghost** [comment]
Hello and thank you for the feedback, great that we could help.

However, the `connectorDeployMode` on `PRODUCTIVE_DEPLOYMENT` does not prevent the artifact from being _sent_ in IDS-Framework version 4.x.y if there is no DAT for the message of the sender of the artifact. The _receiver_ of the message with the artifact and the invalid DAT in the message, on the other hand, discards the message when it is received in this DeployMode because there is no valid DAT in the received message with the artifact. For `TEST_DEPLOYMENT` wiki: "[...] and for received messages, the sent DAT will not be checked.", which is turned on in `PRODUCTIVE_DEPLOYMENT`.

With the Unified-Lib project and IDS-Framework 5, no more messages are sent in `PRODUCTIVE_DEPLOYMENT` which do not have a valid DAT.
