### ISSUE TITLE
"Failed to send the ids message." when running a Producer and a Consumer using Docker

### ISSUE THREAD

**Issue by narcaldas** [FraunhoferISST/DataspaceConnector#178]
Hello, 

I am currently trying to deploy two instances of the connector using Docker. To do this, I built the JAR using the provided instruction in the README.md, and I used the following docker-compose.yml (changed the provided file in the docker-setup.zip of release 3.2.1) and Dockerfile (provided in the docker-setup.zip of release 3.2.1):
[Docker.zip](https://github.com/International-Data-Spaces-Association/DataspaceConnector/files/6103328/Docker.zip)

I used these files because of the reference in [getting started](https://github.com/International-Data-Spaces-Association/DataspaceConnector/wiki/getting-started).

The problem I'm facing is that the connectors don't communicate with each other when using Docker.
First, I did the following test.
Test 1:
```
From: http://localhost:8081/admin/api (Consumer)
POST /admin/api/request/description
URI: https://localhost:8080/api/ids/data (Provider)
Response: Failed to send the ids message.
Logs: consumer-container | 18:05:18.075 [https-jsse-nio-8081-exec-10] WARN - Message could not be sent. [exception=(Failed to connect to localhost/127.0.0.1:8080)] 
```

Also, I tried the following test as stated in [getting started - Docker Setup](https://github.com/International-Data-Spaces-Association/DataspaceConnector/wiki/getting-started#docker-setup).
Test 2:
```
From: http://localhost:8081/admin/api (Consumer)
POST /admin/api/request/description
URI: https://provider:8080/api/ids/data (Provider)
Response: Failed to send the ids message.
Logs: consumer-container | 18:07:31.454 [https-jsse-nio-8081-exec-9] WARN - Message could not be sent. [exception=(Hostname provider not verified:
consumer-container |     certificate: sha256/KgnokG5h8UUUzN0oU2/4v1Fh9m6xoMr9pLOAHv8438U=
consumer-container |     DN: CN=localhost, OU=Unknown, O=Unknown, L=Unknown, ST=Unknown, C=Unknown
consumer-container |     subjectAltNames: [127.0.0.1, localhost])]
```

However, if I run two JARs in the terminal, I'm able to make the communication between the Producer and the Consumer and vice versa (using localhost in the URI).

Also, I tested using this [config.json](https://github.com/International-Data-Spaces-Association/DataspaceConnector/files/6103295/config.zip) file.

Can someone take a look to see if I am missing some configuration?

Thanks in advance.

Best regards,
Narciso Caldas

**Comment by cweiers** [comment]
The outcome of your first test is to be expected:  you're calling https://localhost:8080/api/ids/data, but the call originates from inside the consumer docker container, and there is no server running on that port (because you set the port to 8081 via the environment variable - if you had not done this and left it at the standard 8081:8080 mapping, the consumer would have called himself).

My first guess for your second test would be that you left the application.properties untouched and ssl was still configured. You called a domain "provider", but the certificate in the keystore is for localhost instead. Try to comment out this part:

```
## TLS
#server.ssl.enabled=true
#server.ssl.key-store-type=PKCS12
#server.ssl.key-store=classpath:conf/keystore-localhost.p12
#server.ssl.key-store-password=*******
#server.ssl.key-alias=1
#security.require-ssl=true
```
At least thats how i got two connector instances on a docker setup to talk to each other. 
I think there are plans for a "proper" local docker setup (or a how-to including docker-compose) in the near future from what i gathered.

**Comment by narcaldas** [comment]
@cweiers thank you for your reply.

I also thought the problem was the certificate, but I forgot to try disabling SSL.
I disabled it, and the connectors are communicating now.

Best regards,
Narciso Caldas

**Comment by cweiers** [comment]
Great :)

I just saw that some contributed a local docker setup with a postgres db for both consumer and provider each, so if you want to have a look at it, its under "discussions":

https://github.com/International-Data-Spaces-Association/DataspaceConnector/discussions/188

**Comment by narcaldas** [comment]
Thank you. 
I will take a look at it.
