### ISSUE TITLE
Disable logging to Clearing House

### ISSUE THREAD

**Issue by sebplorenz** [FraunhoferISST/DataspaceConnector#271]
In DSC v5 the logging to a Clearing House is enabled and the following Clearing House is used:

https://ch-ids.aisec.fraunhofer.de/logs/messages/

Logging to this Clearing House results in a 404 and huge error messages and stack traces in the logs.
It would be nice if this logging could be disabled. Either by a config setting or automatically if the clearing.house.url variable is not set.

**Comment by ghost** [comment]
ClearingHouse is undergoing some specification changes, right now the URL should be `/messages/log/` and not `/logs/messages/`. Pre-Specification was changed 4 hours ago. That's why a 404 is returned. (Presumably, the implementation of the CH has already been adapted to the new pre-release specification.)

IDS-G-pre (private repo):
https://github.com/International-Data-Spaces-Association/IDS-G-pre/tree/clearinghouse/Components/ClearingHouse

**Comment by juliapampus** [comment]
As described [here](https://international-data-spaces-association.github.io/DataspaceConnector/Deployment/Configuration#ids-settings): `If you leave the Clearing House address blank, the connector will ignore sending IDS messages to it.` @sebplorenz

**Comment by brianjahnke** [comment]
Since dc293bd3e761611d374bbb3dbc27cd520b6ea0a3 you can also remove the `clearing.house.url` from the `application.propterties`. The behaviour is equivalent to leaving the property blank.
