### ISSUE TITLE
Connection issue to local DAPS instance

### ISSUE THREAD

**Issue by aitorcelaya** [FraunhoferISST/DataspaceConnector#323]
I am trying to build the DSC locally with my own local AISEC DAPS. I found two issues with this:

First, the DAPS requires the "aud" parameter in the payload to refer to the DAPS address (http://localhost:4567). The connector seems to fill the parameter with "ids:IDS_CONNECTORS_ALL".
**Expected by the DAPS:** "aud": "http://localhost:4567"
**DSC default behavior:** "aud": "idsc:IDS_CONNECTORS_ALL"
Where would I go about changing this parameter for the "Request token" payload?

Second, the address for the host DAPS is http:localhost:4567 as I have defined in the src/main/resources/application.properties:

![image](https://user-images.githubusercontent.com/82808687/121366210-97153380-c939-11eb-8ffd-16d7ddb88bae.png)
But, when I executed POST /api/ids/connector/update to register to the Broker to see the DAPS interaction in the logs I see the following:

![image](https://user-images.githubusercontent.com/82808687/121367124-5538bd00-c93a-11eb-86de-0f82e5e4da4c.png)
The DSC tries to pull a token from http://localhost:4567/v2/token (Notice the /v2 different from line 59 in the first image). It also does recognize the http://localhost:4567 as it shows in the WARN below the ERROR. I do know that the /v2 is a custom path that the daps.aisec.fraunhofer.de DAPS uses. Is there any way around that?

**Comment by ghost** [comment]
Hello and thank you for the feedback!

The second point is due to the IDS-Framework. The class for managing the DAPS DAT was formerly programmed specifically for the AISEC DAPS, therefore the extension `/v2/token` is also specified there. I will write an issue for this in the IDS-Framework. Affected IDS-Framework line:
https://github.com/International-Data-Spaces-Association/IDS-Connector-Framework/blob/527cf0fee9b7bb5b5c5c4590e964b91e493c818e/base/src/main/java/de/fraunhofer/isst/ids/framework/daps/TokenManagerService.java#L138

Outlook:
With the IDS-Messaging-Services, this is no longer a problem. IDS-Messaging-Services line:
https://github.com/International-Data-Spaces-Association/IDS-Messaging-Services/blob/14c420f4cfa30759a2d18093cca1ce12520d18fc/core/src/main/java/de/fraunhofer/ids/messaging/core/daps/aisec/AisecTokenManagerService.java#L103

**Comment by ghost** [comment]
The first issue is also part of the IDS-Framework & IDS-Messaging-Services, we need to take a closer look at the DAPS-specification here, what the DAPS expects.

Code-Line IDS-Framework:
https://github.com/International-Data-Spaces-Association/IDS-Connector-Framework/blob/2d0bbf20f1cb5f89104de0516d97cad95db8b162/base/src/main/java/de/fraunhofer/isst/ids/framework/daps/TokenManagerService.java#L49

Code-Line IDS-Messaging-Services:
https://github.com/International-Data-Spaces-Association/IDS-Messaging-Services/blob/5e0262d23f513f9310e4a5ba143e05b52f1eddf2/core/src/main/java/de/fraunhofer/ids/messaging/core/daps/aisec/AisecTokenManagerService.java#L79

I will write an Issue in both projects and clarify the specification.

**Comment by ghost** [comment]
Status update:
- The hardcoded /v2/token will be fixed today with release of a new IDS-Framework version
- aud:"ids:IDS_CONNECTORS_ALL" -> if I change the audience to the AISEC DAPS-URL (Base-URL or with /v2.. as suffix), the DAPS answers me:
`Error retrieving token: Unexpected code Response{protocol=http/1.1, code=400, message=Bad Request, url=https://daps.aisec.fraunhofer.de/v2/token}`
-> I can't just simply use the DAPS-URL as JWT audience, only the wildcard currently works for me, needs to be clarified with AISEC DAPS. I will leave it as it is for the time being, since it technically works right now.
