### ISSUE TITLE
Data consumption scenario (localhost)

### ISSUE THREAD

**Issue by mikhail-gordienko** [FraunhoferISST/DataspaceConnector#362]
**Description:**

Data consumption does not work when a connector requests its own meta. 
Connector's self-description does not get rendered.

**Steps to reproduce the behavior:**

1. Run the full stack [locally](https://github.com/International-Data-Spaces-Association/IDS-Deployment-Examples/tree/main/dataspace-connector/full) **(Disable security)**
2. Go to Consumption tab in Configuration Manager UI
3. Use https://localhost:8080/api/ids/data as "Recipient ID"

**Expected behavior:**
Information gets rendered

**Actual behavior:**
UI gets stuck, but the response is OK, it can be viewed in the debug console.

**Screenshots:**
![freeze](https://user-images.githubusercontent.com/84075862/122749837-db3ff680-d29e-11eb-885c-e54025b343cb.PNG)

**Desktop:**
 - OS: Windows
 - Browser chrome
 - Version 91.0.4472.106 (Official Build)

**Additional context:**
The goal of this scenario is to show data offering and data consumption using the same connector.

**Comment by brianjahnke** [comment]
Hi,
which version of the Dataspace Connector are you using?

**Comment by ghost** [comment]
IDS-Deployment-Examples _full_ is used: Dataspace Connector v4.3.1

My quick guess: In general, I would advise to not try to consume data from the same connector as the one who also offers them and thus consume its own resources. Under certain circumstances this can lead to problems with the serialization in the CM-backend, since some resources will be offered and consumed at the same time. At least this has been a problem before, when there were two resources with the same ID but different media-type-ID. If this still causes a problem, we'd have to look at it for CM v7.

**Comment by MikhailGordienk** [comment]
Hello!

Thank you for your feedback. Unfortunately, it is the same with two connectors. I tried it with v 4.3.0. Again, I saw the response had come in the Chrome debug console, but the page was not responding.
