### ISSUE TITLE
Feature: subscription pattern implementation

### ISSUE THREAD

**Issue by juliapampus** [FraunhoferISST/DataspaceConnector#385]
A consumer connector should be able to subscribe to consumed resources or artifacts. We will use the generic `RequestMessage` to subscribe or unsubscribe, but would need a `SubscribeMessage` with e.g. a `targetElement` for what update messages should be received as attribute. Correspondingly, there would also have to be an `UnsubscribeMessage`.

To implement:
- [x] A controller method to initiate `RequestMessages`. Via this REST endpoint `ids/subscribe` and `ids/unsubscribe`, an IDS message will be sent to the provider connector. The endpoint needs at least the parameter `recipient` and a request body containing further information (see below).  
- [x] A message handler to process incoming `RequestMessages` at `.../api/ids/data`. Does the message refers to a resource, update messages will be sent for any resource metadata update. If the message refers to an artifact, a `ResourceUpdateMessage` will be sent on metadata changes (artifact or resource level), the data will be pushed to the consumer (via [`UploadMessage`](http://htmlpreview.github.io/?https://github.com/International-Data-Spaces-Association/InformationModel/blob/feature/message_taxonomy_description/model/communication/Message_Description.htm)). If the connector unsubscribes, this will be also handled.
- [x] Before pushing the data, the provider would need to check the contract agreement for any policy restriction.
- [x] International-Data-Spaces-Association/DataspaceConnector#18
- [x] ~~A message handler to process incoming `UploadMessages` at `.../api/ids/data`. The artifact to store the data cannot be identified via `transferContract`. The message has no useful attribute, how to refer to an artifact id?~~
- [x] Handle `ResourceUpdateMessages`: notify subscribers to requested resource id.
- [x] Notify subscribers on database event.
- [x] Notify subscribers manually at `GET /notify`.

The subscription object can look as follows (https://stripe.com/docs/api/webhook_endpoints/list, https://web.archive.org/web/20120302000920/http://wiki.webhooks.org/w/page/13385128/RESTful%20WebHooks):
- id: automatically created (read-only)
- target: id of the resource or artifact
- created + modified (metadata): datetime of subscription and changes (read-only)
- title + description: human readable text
- status: enabled, disabled
- events: updated (`ResourceUpdateMessage`), deleted (`ResourceUnavailableMessage`)
- url: where to expect the `ResourceUpdateMessage`, `ResourceUnavailableMessage`, or `UploadMessage`
- issuer: URI (connector or backend system id, participant id) (read-only)
- (logs: list of logs that archives every event (containing issuerConnector, timestamp, messageId, address) (read-only))

To distinguish between ids and backend subscriptions, we need a flag in the database entry. Do we? IDS subscriptions refer to resource offers and backend subscriptions to requested resources. Still, a consumer connector has to somehow store its own subscriptions to other connectors for requested resources. --> attribute `tag`: active, passive? ids, non-ids?
- [x] Subscriptions can be managed via `api/subscriptions`.
- [x] Provide application credentials to access this part of the REST API.
- [x] Subscriptions can be added to requested resources via `api/requests/subscriptions`.
- [x] Subscriptions via ids will be handled automatically, can be accessed at `api/offers/subscriptions`.

Additional features to improve the approach above (later):
- [x] Open endpoint for backend systems to subscribe, instead of needing an admin with access rights for the API.

**Comment by thilo20** [comment]
// I think this feature is the best match for my 'event data streaming' use case 😄 

To make this more prominent / explicit:
Currently, the `ResourceUpdateMessage` is intended for Broker information only - not for provider-consumer communication. Right?
```
POST ​/api​/ids​/resource​/update   Resource update message
Can be used for registering or updating a resource at an IDS broker.
- recipient required
- resourceId required
```
Is the recipient a broker - or can it also be a connector? (if so, what happens there?)

What we want to achieve (in general / by *this feature*) is provider-consumer communication to notify about resource updates (e.g. **new event data available for pick-up**, provided via a single ITS resource/artifact). 
To make this work end-to-end..
1. how can my internal system inform my provider about resource changes? 
(i.e. local updates of 'remote data' =artifact with accessUrl) 
*originally we thought ResourceUpdateMessage is intended for this*
2. how can the consumer inform a downstream system? 
(so that it can fetch the new events via `GET consumer../artifact-id/data/<custom query>`,
 on demand, no auto-download but without much delay)

As a resource can be subscibed by several consumers, we would like to understand if update notifications need to be sent manually and to each consumer of a resource - or just 1 operation on the provider-side is required?
Maybe we need both a multiplex and a throttle (in case of too many updates) mechanism.

I'm glad for feedback/corrections/confirmation, Thilo

**Comment by juliapampus** [comment]
`Currently, the ResourceUpdateMessage is intended for Broker information only - not for provider-consumer communication. Right?`
No, this message can also be used for updating resources at a consumer connector, as described [here](https://international-data-spaces-association.github.io/DataspaceConnector/CommunicationGuide/Provider#resource-updates) and [here](https://international-data-spaces-association.github.io/DataspaceConnector/CommunicationGuide/Consumer#resource-updates).

`As a resource can be subscibed by several consumers, we would like to understand if update notifications need to be sent manually and to each consumer of a resource - or just 1 operation on the provider-side is required?`
This message would now have to be sent manually, but will be automated with this feature.

To 1), I have to think about this. The `ResourceUpdateMessage` is not intended for that as it refers to the communication between two IDS participants, not the backend system and the connector. But I only thought about updating backend systems on consumer side on data changes, not informaing the provider connector on data changes of the provider's backend.

To 2), see 1). Backend systems will be able to subscribe so they get informed about data changes. Then, a new data request can be performed.
