### ISSUE TITLE
ArtifactResponseMessage - Unexpected character ('/' (code 47))

### ISSUE THREAD

**Issue by ctoscano-eu** [FraunhoferISST/DataspaceConnector#479]
On the 6.0.0, I am getting an error coming from the ArtifactResponseMessage.

Please see line 8 on the attached file (connector's log)

[New Text Document (4).txt](https://github.com/International-Data-Spaces-Association/DataspaceConnector/files/6910780/New.Text.Document.4.txt)

**Comment by ghost** [comment]
Error log message is no longer printed as of IDS-Messaging-Services v4.3.0. Is logged during the evaluation of the SecurityProfile by the Infomodel-Serializer, which can not parse the payload. As a solution we now check in advance before input into the Serializer whether the payload would be parsable by the Serializer, if not, we skip this part.

Changelog 4.3.0:
`The payload of incoming messages is now first validated for valid JSON and whether the securityProfile attribute is present, if not, this check is skipped instead of issuing an error message in the logs (IdsHttpService checkDatFromResponse).`
