### ISSUE TITLE
Unable to launch DSC

### ISSUE THREAD

**Issue by aitorcelaya** [FraunhoferISST/DataspaceConnector#575]
I was following the Get Started section of the documentation:

"If you want to build and run locally, ensure that at least Java 11 is installed. Then, follow these steps:

Clone the repository: git clone https://github.com/International-Data-Spaces-Association/DataspaceConnector.git.
Execute cd DataspaceConnector and ./mvnw clean package."

I successfully downloaded the repo and followed the steps. This is the result I get: 

WARNING: Tests run: 1516, Failures: 0, Errors: 0, Skipped: 1

Followed by a BUILD FAILURE as you can see from the picture. It mentions "unknown host repo.maven.apache.org"

![image](https://user-images.githubusercontent.com/82808687/132532703-0e5698f7-6abb-470d-8100-8c9239630979.png)

I am currently using Ubuntu 20.04, and the VM can successfully run the previous DSC instantce we had, v5.1.2.

Thank you in advance.

**Comment by ghost** [comment]
Please just try again, the tests can also be disabled under Profiles "no-tests", which speeds up the build process a little bit. It seems that an artifact of Maven-Central could not be read, what can happen from time to time. If it still doesn't work, please let us know. (Could also be due to local proxy settings etc.)

This is the dependency: https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-buildpack-platform/2.5.4

**Comment by juliapampus** [comment]
@aitorce Is this still an unsolved issue?

**Comment by aitorcelaya** [comment]
The connector is working as intented. Thank you for the responses!

**Comment by ghost** [comment]
👍
