### ISSUE TITLE
Different ID formats for Rule Action

### ISSUE THREAD

**Issue by MikhailGordienk** [FraunhoferISST/DataspaceConnector#643]
**Describe the bug**

[This section](https://international-data-spaces-association.github.io/DataspaceConnector/CommunicationGuide/v6/Consumer#step-3-negotiate-a-contract-agreement) describes a contract request format, and the specified Action is _idsc:USE_. On the other hand, the sample policy provided by `/api/examples/policy` has a different action format (URL):

```
POST  /api/examples/policy
{
    "type": "PROVIDE_ACCESS",
    "title": "cillum et",
    "description": "in et velit mollit"
}
```
```
{
  "@context" : {
    "ids" : "https://w3id.org/idsa/core/",
    "idsc" : "https://w3id.org/idsa/code/"
  },
  "@type" : "ids:Permission",
  "@id" : "https://w3id.org/idsa/autogen/permission/43f3b3ae-eaef-46a8-b4af-73b13c4da545",
  "ids:title" : [ {
    "@value" : "Allow Data Usage",
    "@type" : "http://www.w3.org/2001/XMLSchema#string"
  } ],
  "ids:description" : [ {
    "@value" : "provide-access",
    "@type" : "http://www.w3.org/2001/XMLSchema#string"
  } ],
  "ids:assigner" : [ ],
  "ids:assignee" : [ ],
  "ids:postDuty" : [ ],
  "ids:constraint" : [ ],
  "ids:action" : [ {
    "@id" : "https://w3id.org/idsa/code/USE"
  } ],
  "ids:preDuty" : [ ]
}
```

**Desktop (please complete the following information):**
 - Version 6.2.0

**Additional context**

_Full_ docker-compose from Examples

**Comment by juliapampus** [comment]
Hi @MikhailGordienk, thanks for the question! This should not have any impact on the DSC's functionality and API. From an ontology perspective, `https://w3id.org/idsa/code/USE` and `idsc:USE` mean the same. As you can test with the validation endpoint, the connector recognizes both expressions. That the example differs from the DSC's response is due to Infomodel serializer library changes that print out the action information differently since some newer version. The documentation just provides some examples. We cannot guarantee that it is always 100% consistent with every JSON-LD object, as RDF sometimes does not only provide one possible solution for expressing the same information.
