### ISSUE TITLE
Facing issue in consumer to get data: IDS connector v6.1.2 provider and consumer set up

### ISSUE THREAD

**Issue by sachinargade123** [FraunhoferISST/DataspaceConnector#647]
**Describe the bug**

We tried to configure provider and consumer for DSC v6.2.1 (https://github.com/International-Data-Spaces-Association/DataspaceConnector).

We have followed the documentation https://international-data-spaces-association.github.io/DataspaceConnector/CommunicationGuide/v6/Provider for provider
and https://international-data-spaces-association.github.io/DataspaceConnector/CommunicationGuide/v6/Consumer for consumer set up.

We have documented all steps which we followed based on documentation while doing data set up for provider and consumer. Please find attachment.

[Steps.to.be.done.for.DSC.v.6 (1).pdf](https://github.com/International-Data-Spaces-Association/DataspaceConnector/files/7260474/Steps.to.be.done.for.DSC.v.6.1.pdf)

We need to get reviewed all steps which we followed are correct or not?
In consumer set up for step 3 and step 4 as mentioned in document we have below issues/Questions:

Question or Issues:

How we can Negotiate a Contract Agreement at consumer end? is the request format we used in consumer set up at step 3 is correct?
We tried to set contract agreement but we got below error .
{
"reason": {
"properties": null,
"@id": "https://w3id.org/idsa/code/NOT_FOUND"
},
"payload": "Could not find any matching contract offers for your request.",
"type": "de.fraunhofer.iais.eis.RejectionMessageImpl"
}
How the data available or accessible at consumer end which created at provider end?
In consumer set up step 4 we tried Access data but did not get expected response.
{
"message": "Resource not found."
}

**Comment by juliapampus** [comment]
Hi @sachinargade123, I have already replied to your mail on 28.09. and provided a solution to your problem. Maybe you can take a look or contact your colleagues. To quote myself:
```
To question/issue 1: I guess your problem is the contract on the provider side. I see from the PDF that the consumer "https://localhost:8081/" is defined there. If you started the application without changing any configuration (as seen on page 1), both your connectors have the default id from the repository, which is " https://w3id.org/idsa/autogen/baseConnector/7b934432-a85e-41c5-9f65-669219dde4ea". During the contract negotiation, the DSC compares the id from the issuing connector (consumer) to the consumer id that was defined within the contract by the provider. As there is no match, you are getting the rejection reason. 

Two possible solutions for that:
1. (Sufficient for local deployment and testing) Skip the consumer when creating the contract. The DSC will only compare the values if they are set.
2. (Necessary in the long run anyway) Give your connector a unique id: https://international-data-spaces-association.github.io/DataspaceConnector/Deployment/Configuration#step-2-ids-certificate. And check all other configurations as well.

To question/issue 2: Your data access does not work, as the artifact will have a new uuid on the consumer side. As long as the contract negotiation wasn’t successful, the consumer connector will not create an artifact and download the data. When you then try to access the artifact by the provider’s uuid on the consumer side, the connector does not know this object. So, as soon as step 1 works, I expect issue 2 being solved as well.
```

**Comment by SebastianOpriel** [comment]
Hi @juliapampus, one inquiry: 
You mentioned a Connector's default ID is: `7b934432-a85e-41c5-9f65-669219dde4ea`
But at DAPS it is said to be `SKI:AKI` (see https://github.com/International-Data-Spaces-Association/IDS-G-pre/tree/main/Components/IdentityProvider/DAPS#unique-identifier)
Do I mix up things?

**Comment by juliapampus** [comment]
@bastianleirpo No, I said the (not a) connector's default id is `https://w3id.org/idsa/autogen/baseConnector/7b934432-a85e-41c5-9f65-669219dde4ea` - not the uuid. This is because the id is generated when building the RDF object with the Infomodel serializer (see [this](https://international-data-spaces-association.github.io/DataspaceConnector/Deployment/Configuration#step-1-connector-properties) example string). Therefore, the documentation says that you should change the id before the deployment: https://international-data-spaces-association.github.io/DataspaceConnector/Deployment/Configuration#step-2-ids-certificate.

In my understandig, this SKI/AKI is something different than the connector's id inside its self-description. According to the Infomodel, this has to be a URI. And as once discussed with @sebbader, this could be e.g. the connector's URL. To ensure that connectors do not pretend to be other connectors, the DAPS would have to check from where an incoming DAT request comes and if this fits to the DNS entry they expect for the registered connector.

**Comment by sachinargade123** [comment]
@juliapampus I got your response. I will check and get back with the result.
