### ISSUE TITLE
Error at the endpoints for app store handling

### ISSUE THREAD

**Issue by jfernandezsqs** [FraunhoferISST/DataspaceConnector#836]
**Describe the bug**
I have installed a DSC version 6.2.0 and follow the documentation (https://international-data-spaces-association.github.io/DataspaceConnector/CommunicationGuide/v6/IdsEcosystem/AppStore#step-2-create-app-store-entity) 
But when I delete this app sotre ID and try to create another one with the same arguments it is giving an error message.

**To Reproduce**
1. Create the following App Store
>POST /api/appstores
 {
  "title": "Example AppStore",
  "description": "Some description",
  "location": "https://binac.fit.fraunhofer.de/api/ids/data"
}

Response body:
![image](https://user-images.githubusercontent.com/82888094/149312404-a6ee1053-fe31-4675-b5c9-3ad94e0b26c4.png)
2. Delete the App Store created
> DELETE /api/appstores/{id}
![image](https://user-images.githubusercontent.com/82888094/149312499-deed8321-722b-45c2-bb26-a057e7ec4443.png)
3. Create again the App Store
>POST /api/appstores
 {
  "title": "Example AppStore",
  "description": "Some description",
  "location": "https://binac.fit.fraunhofer.de/api/ids/data"
}
![image](https://user-images.githubusercontent.com/82888094/149312704-670ec40a-0b8a-4145-8c0a-b46019d6609a.png)

**Expected behavior**
It should be possible to create the App via the Swagger UI call of Step 3.

**Comment by ghost** [comment]
Looks to me like deleting an AppStore only sets a flag for deleted to `true` and does not remove the AppStore itself. At the same time, however, it is required to have the `location` unique in the database. So after _deleting_ the old AppStore-entry still exists with `deleted=true`, and when trying to add a new AppStore-entry with the same `location`, it fails because of the unique location-requirement in the AppStore-table.

https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/8f685199b061326cdce9a531893488c85530c0b2/src/main/java/io/dataspaceconnector/model/appstore/AppStore.java#L41

https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/8f685199b061326cdce9a531893488c85530c0b2/src/main/java/io/dataspaceconnector/model/appstore/AppStore.java#L57

**Comment by jfernandezsqs** [comment]
Is this the expected operation? 
because if so, it is not possible to recreate an app store with that location once deleted.

**Comment by brianjahnke** [comment]
Hi,
no it is not.
